### ISSUE TITLE
Problème avec PHP 8.1.16

### ISSUE THREAD

**Issue by stf4-Sony** [Piwigo/ExtendedDescription#14]
Bonjour 

Je rencontre des problèmes d'affichage du plugin 

Deprecated: substr_count(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www//plugins/ExtendedDescription/include/events.inc.php on line 331

Merci a qui aura une solution pour corriger le problème.

BD

**Comment by git-emil** [comment]
Hi!

I'm facing the very same error message after upgrading from v12 to v13 and switching to php 8.1.
After changing the code to this:

> if (substr_count($pictures[$i]['name'] ?? "", $conf['ExtendedDescription']['not_visible']))
   
the problem seems to be solved. But I am not 100% sure; the source code is missing meaningful comments.

Emil
