### ISSUE TITLE
Compatibility with php 8.1

### ISSUE THREAD

**Issue by git-emil** [Piwigo/ExtendedDescription#9]
After switching to php 8.1 I found two warnings. 

1.
> Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /.../piwigo13/plugins/ExtendedDescription/include/events.inc.php on line 102

Current code:
```
102: return preg_replace($patterns, $replacements, $desc');
```

Fix:
```
102: return preg_replace($patterns, $replacements, $desc ?: '');
```

2.
> Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /.../piwigo13/plugins/ExtendedDescription/include/events.inc.php on line 120

Current code:
```
123: and preg_match('#\[redirect (.*?)\]#i', $desc, $m1)
```

Fix:
```
123: and preg_match('#\[redirect (.*?)\]#i', $desc ?: '', $m1)
```

At least this seems to fix it for me :-)

**Comment by plegall** [comment]
was fixed by f31429292e5b20ff8f2ce372de1fe63f2b42c90d
